import Link from "next/link";
import { notFound } from "next/navigation";
import { books, getBook } from "@/data/bible";
import { getChapter } from "@/lib/bible";

type Props = { params: Promise<{ book: string; chapter: string }> };
export function generateStaticParams() { return books.flatMap((book) => Array.from({ length: book.chapters }, (_, index) => ({ book: book.slug, chapter: String(index + 1) }))); }

export default async function ChapterPage({ params }: Props) { const { book: slug, chapter: chapterParam } = await params; const book = getBook(slug); const chapter = Number(chapterParam); if (!book || !Number.isInteger(chapter) || chapter < 1 || chapter > book.chapters) notFound(); const verses = getChapter(book, chapter); return <main><section className="border-b border-border"><div className="mx-auto max-w-4xl px-6 py-14 lg:py-20"><div className="flex flex-wrap items-center gap-3 text-sm text-muted"><Link href="/read" className="hover:text-foreground">Firman</Link><span>/</span><Link href={"/read/" + book.slug} className="hover:text-foreground">{book.name}</Link><span>/</span><span>Pasal {chapter}</span></div><h1 className="mt-6 font-serif text-5xl tracking-tight sm:text-7xl">{book.name} {chapter}</h1></div></section><article className="mx-auto max-w-3xl px-6 py-16 lg:py-24">{verses.length > 0 ? <div className="space-y-8">{verses.map((verse) => <p key={verse.id} className="font-serif text-[1.35rem] leading-[1.7]"><sup className="mr-3 font-sans text-xs font-semibold text-primary">{verse.verse}</sup>{verse.text}</p>)}<p className="border-t border-border pt-8 text-xs leading-6 text-muted">Teks Alkitab: Alkitab Yang Terbuka (AYT), © Yayasan Lembaga SABDA (YLSA).</p></div> : <div className="rounded-[28px] border border-border bg-surface p-8 sm:p-10"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-primary">Dataset belum tersedia</p><h2 className="mt-5 font-serif text-3xl">Siap untuk teks AYT.</h2><p className="mt-5 text-sm leading-7 text-muted">Jalankan <code className="rounded bg-surface-muted px-1.5 py-0.5">npm run ingest:bible</code> sebelum production build. Script mengambil data AYT saat ingestion dan menyimpannya sebagai data statis; situs tidak memanggil API AYT ketika pengunjung membaca halaman ini.</p></div>}<div className="mt-12 flex items-center justify-between gap-4 border-t border-border pt-6"><Link href={chapter > 1 ? "/read/" + book.slug + "/" + (chapter - 1) : "/read/" + book.slug} className="text-sm font-semibold text-primary">← Sebelumnya</Link><Link href={chapter < book.chapters ? "/read/" + book.slug + "/" + (chapter + 1) : "/read"} className="text-sm font-semibold text-primary">{chapter < book.chapters ? "Berikutnya →" : "Kembali ke kitab →"}</Link></div></article></main>; }
