import Link from "next/link";
import { searchLocal } from "@/lib/search";

type Props = { searchParams: Promise<{ q?: string }> };
export const metadata = { title: "Cari", description: "Cari ayat dan topik melalui indeks kurasi lokal Sela." };

export default async function SearchPage({ searchParams }: Props) {
  const params = await searchParams;
  const query = (params.q ?? "").trim();
  const results = query ? searchLocal(query) : [];
  const examples = ["aku takut masa depan", "aku merasa sendirian", "aku bingung memilih", "aku butuh pengharapan"];
  return <main><section className="border-b border-border"><div className="mx-auto max-w-4xl px-6 py-20 lg:py-28"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-primary">Search</p><h1 className="mt-5 font-serif text-5xl tracking-tight sm:text-7xl">Apa yang sedang kamu cari?</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-muted">Cari berdasarkan keadaan, pertanyaan, atau topik yang sedang kamu bawa.</p><form className="mt-10 flex flex-col gap-3 sm:flex-row" action="/search"><input name="q" defaultValue={query} placeholder="Contoh: aku takut masa depan" aria-label="Cari ayat atau topik" className="min-h-12 flex-1 rounded-full border border-border bg-surface px-5 outline-none placeholder:text-muted focus:border-primary"/><button type="submit" className="min-h-12 rounded-full bg-primary px-6 text-sm font-semibold text-primary-foreground transition hover:opacity-90">Cari</button></form></div></section><section className="mx-auto max-w-4xl px-6 py-14 lg:py-20">{query && results.length > 0 ? <div><div className="flex items-center justify-between gap-6"><h2 className="font-serif text-2xl">Hasil untuk “{query}”</h2><span className="text-sm text-muted">{results.length} hasil</span></div><div className="mt-7 space-y-3">{results.map((result, index) => <Link key={result.href + index} href={result.href} className="block rounded-2xl border border-border bg-surface p-6 transition hover:border-primary"><span className="text-xs font-semibold uppercase tracking-[0.14em] text-muted">{result.type === "mood" ? "Mood" : "Ayat"}</span><h3 className="mt-3 font-serif text-2xl">{result.title}</h3><p className="mt-2 text-sm leading-7 text-muted">{result.description}</p></Link>)}</div></div> : query ? <div className="rounded-[28px] border border-border bg-surface p-8 sm:p-10"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-muted">Belum menemukan kecocokan</p><h2 className="mt-4 font-serif text-3xl">Coba ungkapkan dengan kata lain.</h2><p className="mt-4 max-w-xl text-sm leading-7 text-muted">Gunakan keadaan atau topik yang sederhana, misalnya “takut”, “bimbang”, “butuh kekuatan”, atau nama kitab.</p></div> : <div className="grid gap-3 sm:grid-cols-2">{examples.map((example) => <Link key={example} href={"/search?q=" + encodeURIComponent(example)} className="rounded-2xl border border-border bg-surface p-5 text-sm font-semibold transition hover:border-primary">{example}</Link>)}</div>}</section></main>;
}
